import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import fs from 'node:fs';
import path from 'node:path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

if (prod) {
	const outfile = 'main.js';
	console.log(`[build] start production build -> ${outfile}`);
	const result = await context.rebuild();
	if (result.errors && result.errors.length > 0) {
		console.error(`[build] failed with ${result.errors.length} error(s).`);
		await context.dispose();
		process.exit(1);
	}
	try {
		const stat = fs.statSync(path.resolve(outfile));
		const kb = (stat.size / 1024).toFixed(2);
		console.log(`[build] done. output: ${outfile} (${kb} KB)`);
	} catch (e) {
		console.log('[build] done, but output file not found:', e.message);
	}
	await context.dispose();
	process.exit(0);
} else {
	await context.watch();
}
